apiVersion: apps/v1
kind: Deployment
metadata:
  name: irys-app-deploy
  namespace: irys-ui
  labels:
    app: irys-app
spec:
  replicas: 1 # Consider scaling for higher availability
  selector:
    matchLabels:
      app: irys-app
  template:
    metadata:
      labels:
        app: irys-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - irys-app
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: irys-app-container
          image: gcr.io/kxn-dev-432901/kxn-dev/irys-ui-img:122
          ports:
            - containerPort: 80  # Only HTTP, since HTTPS is handled by NGINX Ingress
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
          securityContext:
            runAsNonRoot: true  # Enforce running as a non-root user
            allowPrivilegeEscalation: false  # Prevent privilege escalation
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 80  # Adjust probe to check HTTP (port 80)
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80  # Adjust probe to check HTTP (port 80)
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
