apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: irys-app-hpa
  namespace: irys-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: irys-app-deploy
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 
